name: continuous_integration
on: ["push", "pull_request"]
jobs:
  ping:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
      - run: conda --version
      - run: which python
      - name: Install dependencies
        run: conda install -c conda-forge selenium geckodriver
      - name: Ping
        run: ./ping.py
